[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/